on:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:
name: Continuous Integration

permissions:
  pull-requests: read
  
jobs:
  lint:
    name: Check code-style using dotnet-format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'

    - name: Run dotnet-format
      uses: zyactions/dotnet-format@v1
      with:
        workspace: Netherlands3D.sln
        verify-no-changes: true
        implicit-restore: true