on:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:
name: Continuous Integration

permissions:
  pull-requests: read
  
jobs:
  lint:
    name: Check code-style using dotnet-format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Add dotnet-format problem matcher
      uses: xt0rted/dotnet-format-problem-matcher@v1

    - name: Restore dotnet tools
      uses: xt0rted/dotnet-tool-restore@v1

    - name: Run dotnet format
      uses: xt0rted/dotnet-format@v1
      with:
# enable again in the final version; but now nothing is checked
#        only-changed-files: "true"
        action: "check"